# abireport
# Autogenerated from man page /usr/share/man/man1/abireport.1
complete -c abireport -s p -l prefix --description '.'
complete -c abireport -s D -l output-dir --description '.'
complete -c abireport -s h -l help --description '.'

