# btrfstune
# Autogenerated from man page /usr/share/man/man8/btrfstune.8.gz
complete -c btrfstune -s S --description 'Enable seeding on a given device.'
complete -c btrfstune -s r --description '(since kernel: 3. 7) .'
complete -c btrfstune -o 'u.' --description 'Warning Cancelling or interrupting a UUID change operation will make the file…'

