# clr-boot-manager
# Autogenerated from man page /usr/share/man/man1/clr-boot-manager.1
complete -c clr-boot-manager -s h -l help --description 'Prints a help message.'
complete -c clr-boot-manager -s p -l path --description 'Set the base path for boot management operations.'
complete -c clr-boot-manager -s i -l image --description 'Force clr-boot-manager to run in image mode.'
complete -c clr-boot-manager -s v -l version --description 'Print the version of clr-boot-manager  and exit.'

