# gnome-mpv
# Autogenerated from man page /usr/share/man/man1/gnome-mpv.1.gz
complete -c gnome-mpv -s '?' -s h -l help --description 'Show help options.'
complete -c gnome-mpv -l new-window --description 'Create a new window if there is already a running instance.'
complete -c gnome-mpv -l enqueue --description 'Append the given files or URIs to the playlist if there is a running instance.'
complete -c gnome-mpv -l version --description 'Print the release version and exit.'

