# goofiboot
# Autogenerated from man page /usr/share/man/man8/goofiboot.8
complete -c goofiboot -s h -l help --description 'Prints a short help text and exits.'
complete -c goofiboot -l path --description 'Path to the EFI system partition.  The default is /boot.'
complete -c goofiboot -l no-variables --description 'Do not touch the EFI boot variables.'
complete -c goofiboot -l force --description 'Force install,remove,update even if ESP validation fails.'

