# klavaro
# Autogenerated from man page /usr/share/man/man1/klavaro.1
complete -c klavaro -s h -l help: --description '.'
complete -c klavaro -s v -l version: --description 'COLORS Some colors may be configured through the file "preferences.'

