# libinput-debug-events
# Autogenerated from man page /usr/share/man/man1/libinput-debug-events.1
complete -c libinput-debug-events -l help --description 'Print help.'
complete -c libinput-debug-events -l show-keycodes --description 'Key events shown by this tool are partially obfuscated to avoid passwords and…'

