# mbim-network
# Autogenerated from man page /usr/share/man/man1/mbim-network.1
complete -c mbim-network -l profile --description 'Use the profile in the specified path.'
complete -c mbim-network -l help --description 'Show help options.'
complete -c mbim-network -l version --description 'Show version . PP Notes:.'

