# midicat
# Autogenerated from man page /usr/share/man/man1/midicat.1
complete -c midicat -s d --description 'Dump transferred data in hex on stderr.'
complete -c midicat -s i --description 'Use this sndio 7 MIDI port as input instead of stdin.'
complete -c midicat -s o --description 'Use this sndio 7 MIDI port as output instead of stdout.'

