# mkfs
# Autogenerated from man page /usr/share/man/man8/mkfs.reiserfs.8
complete -c mkfs -l block-size --description 'N is block size in bytes.'
complete -c mkfs -l hash --description 'HASH specifies which hash function will sort the names in the directories.'
complete -c mkfs -l format --description 'FORMAT specifies the format for the new filsystem.  Choose format 3. 5 or 3.'
complete -c mkfs -s u --description 'Sets  the  Universally  Unique  IDentifier  of  the  filesystem  to  UUID  (s…'
complete -c mkfs -l journal-device --description 'FILE is the name of the block device on which is to be places the  filesystem…'
complete -c mkfs -l journal-offset --description 'N is the offset where the journal starts when it is to be on a separate devic…'
complete -c mkfs -l journal-size --description 'N is the size of the journal in blocks.'
complete -c mkfs -l transaction-max-size --description 'N is the maximum transaction size parameter for the journal.'
complete -c mkfs -s B --description 'File is the file name of the file that contains the list of blocks to be  mar…'

