# osinfo-detect
# Autogenerated from man page /usr/share/man/man1/osinfo-detect.1
complete -c osinfo-detect -l format --description 'Switch between human readable output (plain, the default) or machine readable…'

