# quilt
# Autogenerated from man page /usr/share/man/man1/quilt.1
complete -c quilt -l trace --description '.'
complete -c quilt -l quiltrc --description '.'
complete -c quilt -l version --description '.'
complete -c quilt -s E -s E --description 'no longer be able to deal with empty files, which is why using -E is no longe…'

