# ypkg-install-deps
# Autogenerated from man page /usr/share/man/man1/ypkg-install-deps.1
complete -c ypkg-install-deps -s h -l help --description '.'
complete -c ypkg-install-deps -s v -l version --description '.'
complete -c ypkg-install-deps -s n -l no-colors --description '.'
complete -c ypkg-install-deps -s D -l output-dir --description '.'
complete -c ypkg-install-deps -s f -l force --description '.'

