# ypkg-build
# Autogenerated from man page /usr/share/man/man1/ypkg-build.1
complete -c ypkg-build -s h -l help --description '.'
complete -c ypkg-build -s v -l version --description '.'
complete -c ypkg-build -s n -l no-colors --description '.'
complete -c ypkg-build -s t -l timestamp --description '.'
complete -c ypkg-build -s D -l output-dir --description '.'

