# ypkg
# Autogenerated from man page /usr/share/man/man1/ypkg.1
complete -c ypkg -s h -l help --description '.'
complete -c ypkg -s v -l version --description '.'
complete -c ypkg -s n -l no-colors --description '.'
complete -c ypkg -s D -l output-dir --description '.'
complete -c ypkg -s f -l force --description '.'

